// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	sdk "github.com/voxgig-sdk/flyff-game-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.FlyffGameSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.FlyffGameSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.FlyffGameSDK, name string) (sdk.FlyffGameEntity, error) {
	switch strings.ToLower(name) {
	case "achievement":
		return client.Achievement(nil), nil
	case "awake":
		return client.Awake(nil), nil
	case "badge":
		return client.Badge(nil), nil
	case "class":
		return client.Class(nil), nil
	case "core":
		return client.Core(nil), nil
	case "couple":
		return client.Couple(nil), nil
	case "dungeon":
		return client.Dungeon(nil), nil
	case "element":
		return client.Element(nil), nil
	case "equipment_set":
		return client.EquipmentSet(nil), nil
	case "exchange_menus":
		return client.ExchangeMenus(nil), nil
	case "housing_pack":
		return client.HousingPack(nil), nil
	case "housing_template":
		return client.HousingTemplate(nil), nil
	case "item":
		return client.Item(nil), nil
	case "language":
		return client.Language(nil), nil
	case "lifestyle":
		return client.Lifestyle(nil), nil
	case "monster":
		return client.Monster(nil), nil
	case "npc":
		return client.Npc(nil), nil
	case "party_skill":
		return client.PartySkill(nil), nil
	case "pkn":
		return client.Pkn(nil), nil
	case "place":
		return client.Place(nil), nil
	case "quest":
		return client.Quest(nil), nil
	case "raised_pet":
		return client.RaisedPet(nil), nil
	case "recipe":
		return client.Recipe(nil), nil
	case "skill":
		return client.Skill(nil), nil
	case "upgrade_level_bonus":
		return client.UpgradeLevelBonus(nil), nil
	case "version":
		return client.Version(nil), nil
	case "world":
		return client.World(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
