// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/flyff-game-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"achievement | awake | badge | class | core | couple | dungeon | element | equipment_set | exchange_menus | housing_pack | housing_template | item | language | lifestyle | monster | npc | party_skill | pkn | place | quest | raised_pet | recipe | skill | upgrade_level_bonus | version | world"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.FlyffGameSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "flyff-game_list",
		Description: "List records from FlyffGame. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "flyff-game_load",
		Description: "Load a single record from FlyffGame. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.FlyffGameSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.FlyffGameSDK, name string) (sdk.FlyffGameEntity, error) {
	switch strings.ToLower(name) {
	case "achievement":
		return client.Achievement(nil), nil
	case "awake":
		return client.Awake(nil), nil
	case "badge":
		return client.Badge(nil), nil
	case "class":
		return client.Class(nil), nil
	case "core":
		return client.Core(nil), nil
	case "couple":
		return client.Couple(nil), nil
	case "dungeon":
		return client.Dungeon(nil), nil
	case "element":
		return client.Element(nil), nil
	case "equipment_set":
		return client.EquipmentSet(nil), nil
	case "exchange_menus":
		return client.ExchangeMenus(nil), nil
	case "housing_pack":
		return client.HousingPack(nil), nil
	case "housing_template":
		return client.HousingTemplate(nil), nil
	case "item":
		return client.Item(nil), nil
	case "language":
		return client.Language(nil), nil
	case "lifestyle":
		return client.Lifestyle(nil), nil
	case "monster":
		return client.Monster(nil), nil
	case "npc":
		return client.Npc(nil), nil
	case "party_skill":
		return client.PartySkill(nil), nil
	case "pkn":
		return client.Pkn(nil), nil
	case "place":
		return client.Place(nil), nil
	case "quest":
		return client.Quest(nil), nil
	case "raised_pet":
		return client.RaisedPet(nil), nil
	case "recipe":
		return client.Recipe(nil), nil
	case "skill":
		return client.Skill(nil), nil
	case "upgrade_level_bonus":
		return client.UpgradeLevelBonus(nil), nil
	case "version":
		return client.Version(nil), nil
	case "world":
		return client.World(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
